### ISSUE TITLE
Client-side force closes

### ISSUE THREAD

**Issue by mokhtarabadi** [genshen/wssocks#19] opened 2020-08-06 10:27 UTC
I download the latest version from releases now and set up server-side with status page and HTTP proxy also use haproxy as TLS injector and also run client-side with HTTP proxy support, everything is okay until open connections reach about 50-60 concurrent connections, after that the client-side closes but the server-side still running
for example, I connect Telegram Desktop to proxy and use proxy in firefox and just open one page
I used these commands
for server
`./wssocks-linux-amd64 server -addr :80 -auth -auth_key password -status -http`
and for client
`./wssocks-linux-amd64 client -addr :1080 -http -http-addr :8080 -key password -remote wss://wssocks.**.org:443`

**Comment by genshen** [comment] 2020-08-06 10:43
This may be a **bug** of latest version, I'll check it as soon as possible.  
In fact, if connection at client-side is closed, wssocks should tell server to close this proxy connection immediately.

**Comment by mokhtarabadi** [comment] 2020-08-06 10:45
here is a screencast for this bug [https://mega.nz/file/rxk3QbrS](https://mega.nz/file/rxk3QbrS)

**Comment by mokhtarabadi** [comment] 2020-08-06 10:53
now server-side also closes and I see the output on server-side 
`panic: send on closes channel

goroutine 2053 [running]:
github.com/genshen/wssocks/wss.(*DefaultProxyEst).establish(0xc00000d720, 0xc000b11320, 0x8100f49d2a90b90b, 0x9645a6389d849f1b, 0xa1d29a2d, 0x0, 0xc0000a2ba0, 0x21, 0x0, 0x0, ...)
        /go/src/github.com/genshen/wssocks/wss/proxy_server.go:167 +0x1b1
github.com/genshen/wssocks/wss.establishProxy(0xc000b11320, 0x8100f49d2a90b90b, 0x9645a6389d849f1b, 0xa1d29a2d, 0x0, 0xc0000a2ba0, 0x21, 0x0, 0x0, 0x0)
        /go/src/github.com/genshen/wssocks/wss/proxy_server.go:119 +0xd9
created by github.com/genshen/wssocks/wss.(*Hub).Run
        /go/src/github.com/genshen/wssocks/wss/hub.go:61 +0x215
`

**Comment by genshen** [comment] 2020-08-06 14:31
> here is a screencast for this bug [screencast video](https://mega.nz/file/rxk3QbrS#FtAcARfl4wfLSOQy5TyyrRhujsISQNbRF5d1v0oZcSU)

Could you please attach your log of client? Just the log above "TARGETs-CONNECTIONs table" after client closing (you can hide your privacy information, such as domain or ip address)?  I want to known what error closed the client.
And you can also share your Firefox ***proxy configuration*** if possible.  

Currently, I could not find a way to reproduce this problem on my machine😂. Thanks for for information!

**Comment by mokhtarabadi** [comment] 2020-08-06 14:51
😂😂
Mean you didn't see this bug?
I'm outside now but I trying to test with termux and give you the result
The Firefox, not the problem, because I used tun2socks and redirect whole system traffic, also with that after about 60 active connections, the client closes

**Comment by mokhtarabadi** [comment] 2020-08-06 15:20
I discovered a new bug
For domain resolving you use system DNS resolved or your own?
Because in android when I run the wssocks I see lookup error, but nslookup work

```
INFO[0000] connecting to wssocks server.                 remote="wss://wssocks.****.org:443"
FATA[0000] establishing connection error:failed to WebSocket dial: failed to send handshake request: Get "https://wssocks.****.org:443": dial tcp: lookup wssocks.*****.org on [::1]:53: read udp [::1]:40084->[::1]:53: read: connection refused
```

**Comment by mokhtarabadi** [comment] 2020-08-06 15:39
Okay, when I built whole project inside termux, the wssocks works

**Comment by mokhtarabadi** [comment] 2020-08-06 15:56
Here the last logs of client when closes

```
TARGETs                 CONNECTIONs                  ERRO[0159] write error:read tcp 127.0.0.1:1080->127.0.0.1:44070: use of closed network connection         TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs                  ERRO[0159] write error:read tcp 127.0.0.1:1080->127.0.0.1:44074: use of closed network connection         TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs                  ERRO[0160] write error:read tcp 127.0.0.1:1080->127.0.0.1:44094: use of closed network connection         TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs                  ERRO[0160] error websocket read:failed to read: WebSocket closed: failed to acquire lock: context canceled                                                     TARGETs                 CONNECTIONs                  ERRO[0160] write error:failed to write JSON message: failed to get writer: WebSocket closed: failed to acquire lock: context canceled
TARGETs                 CONNECTIONs
ERRO[0160] failed to write JSON message: failed to get writer: WebSocket closed: failed to acquire lock: context canceled                                      TARGETs                 CONNECTIONs
TARGETs                 CONNECTIONs
TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs                  TARGETs                 CONNECTIONs
TARGETs                 CONNECTIONs
TARGETs                 CONNECTIONs                  ERRO[0160] json error:failed to write JSON message: failed to get writer: WebSocket closed: failed to acquire lock: context canceled                           TARGETs                 CONNECTIONs                  ERRO[0160] close errorfailed to write JSON message: failed to get writer: WebSocket closed: failed to acquire lock: context canceled                           TARGETs                 CONNECTIONs
ERRO[0160] failed to write JSON message: failed to get writer: WebSocket closed: failed to acquire lock: context canceled                                      TARGETs                 CONNECTIONs
TARGETs                 CONNECTIONs
ERRO[0160] listener stopped                                                                               TARGETs                CONNECTIONs
172.217.22.36:443      2
216.58.207.65:443      2
143.204.202.12:443     1                             216.58.212.129:443     1                             216.58.212.163:443     1                             216.58.206.13:443      2                             172.217.23.138:443     1                             104.22.63.209:443      2                             104.131.45.100:443     1                             172.217.18.131:443     1                             172.217.16.168:443     1                             216.58.206.2:443       2
192.95.61.110:443      2
172.67.13.254:443      1
104.131.45.119:443     2                             74.6.138.80:443        1
172.217.18.14:443      1
172.217.18.2:443       1
172.217.16.130:443     1                             172.217.22.106:443     2
20.185.75.141:443      2
216.239.36.117:443     1
172.217.19.174:443     1                             216.58.207.86:443      1                             149.154.167.92:443     4
23.210.250.12:443      3
TOTAL                  127             (48 record(s) hiden)
```

**Comment by genshen** [comment] 2020-08-06 17:15
> ERRO[0160] error websocket read:failed to read: WebSocket closed:

From the log, the reason seems to be that the websocket connection of client is abnormally closed by some reason. (e.g. wssocks server crashing, or even nginx and so on).  
I will continue to track this problem tomorrow.

**Comment by mokhtarabadi** [comment] 2020-08-07 05:55
Hey, so if the problem is the backend, can you add a method to retry connecting instead closing the client, until we send kill signals like ctrl+c 
or client will be close only when server is down

**Comment by mokhtarabadi** [comment] 2020-08-07 05:58
for now, i used wssocks in backend and client like this
`while true; do wssocks [other options]; done;`

**Comment by mokhtarabadi** [comment] 2020-08-08 10:22
another log from the server when connection closed
```
panic: send on closed channel

goroutine 296 [running]:
github.com/genshen/wssocks/wss.(*DefaultProxyEst).establish(0xc00000ed60, 0xc000052840, 0x9dc36388572ebc0b, 0xc9b79db3fea01343, 0xc00f6c1604, 0x0, 0xc00001eb80, 0x18, 0x0, 0x0, ...)
        /home/mohammad/Works/wssocks/wss/proxy_server.go:167 +0x1b1
github.com/genshen/wssocks/wss.establishProxy(0xc000052840, 0x9dc36388572ebc0b, 0xc9b79db3fea01343, 0xf6c1604, 0x0, 0xc00001eb80, 0x18, 0x0, 0x0, 0x0)
        /home/mohammad/Works/wssocks/wss/proxy_server.go:119 +0xd9
created by github.com/genshen/wssocks/wss.(*Hub).Run
        /home/mohammad/Works/wssocks/wss/hub.go:61 +0x215
```

**Comment by genshen** [comment] 2020-08-08 14:26
> another log from the server when connection closed

Thanks your report. This has  been known as a bug. It will be fixed in next patch version.

**Closed** 2020-12-02 09:08 UTC
